version: "3.9"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deploy:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
